{% set name = "dlib" %}
{% set version = "19.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/davisking/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 2bed9669f1a5c436579498d0806b27a9b60c42a975a9b6e67b594b40f58b1a88

  patches:
    - osx_jpeg.patch           # [osx]
    - win_boost.patch
    - win_png.patch            # [win]
    - win_jpeg.patch           # [win]
    - win_release_flags.patch  # [win]

build:
  skip: True                   # [win and py<35]
  number: 0

requirements:
  build:
   - python
   - cmake
   - gcc                          # [linux]
   - numpy
   - boost 1.59.*
   - jpeg 9*                      # [not win]
   - libpng
   - sqlite 3.13.*                # [not win]

  run:
   - python
   - numpy
   - boost 1.59.*
   - jpeg 9*                      # [not win]
   - libpng
   - sqlite 3.13.*                # [not win]

test:
  files:
    - test_data/face.jpg
    - test_data/face.png
    - test_data/images.xml

  requires:
    - tqdm
    - pillow

  imports:
    - dlib

about:
  home: http://dlib.net/
  license: Boost 1.0
  license_file: dlib/LICENSE.txt
  summary: Modern C++ toolkit containing machine learning algorithms with Python bindings
